### ISSUE TITLE
Ubuntu 14.04, Geonode 2.4b22 ==> 500 Internal Server Error

### ISSUE THREAD

**Issue by darabk** [GeoNode/geonode#2090]
After previouse success lunching geonode 2.01 on ubuntu 12.04 and making project for custom theming, for using latest version, jumped to 2.4, but some error appeared..
500 Internal Server Error !

after tracking changes from apache to new version 2.4, error steel exist.

from error.log of apache :

[Tue Mar 03 02:45:09.631507 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424] mod_wsgi (pid=1299): Exception occurred processing WSGI script '/home/dary/my_geonode/my_geonode/wsgi.py'.
[Tue Mar 03 02:45:09.631563 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424] Traceback (most recent call last):
[Tue Mar 03 02:45:09.631596 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Mar 03 02:45:09.631638 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     self.load_middleware()
[Tue Mar 03 02:45:09.631654 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 47, in load_middleware
[Tue Mar 03 02:45:09.631674 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     mw_instance = mw_class()
[Tue Mar 03 02:45:09.631687 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/lib/python2.7/dist-packages/django/middleware/locale.py", line 24, in __init__
[Tue Mar 03 02:45:09.631707 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     for url_pattern in get_resolver(None).url_patterns:
[Tue Mar 03 02:45:09.631720 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 365, in url_patterns
[Tue Mar 03 02:45:09.631739 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Tue Mar 03 02:45:09.631752 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 360, in urlconf_module
[Tue Mar 03 02:45:09.631770 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     self._urlconf_module = import_module(self.urlconf_name)
[Tue Mar 03 02:45:09.631783 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
[Tue Mar 03 02:45:09.631802 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     __import__(name)
[Tue Mar 03 02:45:09.631815 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/home/dary/my_geonode/my_geonode/urls.py", line 4, in <module>
[Tue Mar 03 02:45:09.631833 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     from geonode.urls import *
[Tue Mar 03 02:45:09.631846 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/local/lib/python2.7/dist-packages/geonode/urls.py", line 30, in <module>
[Tue Mar 03 02:45:09.631865 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     from geonode.api.urls import api
[Tue Mar 03 02:45:09.631878 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/local/lib/python2.7/dist-packages/geonode/api/urls.py", line 3, in <module>
[Tue Mar 03 02:45:09.631910 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     from .api import TagResource, TopicCategoryResource, ProfileResource, \\
[Tue Mar 03 02:45:09.631935 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/local/lib/python2.7/dist-packages/geonode/api/api.py", line 21, in <module>
[Tue Mar 03 02:45:09.631958 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     from tastypie.resources import ModelResource
[Tue Mar 03 02:45:09.631972 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/lib/python2.7/dist-packages/tastypie/resources.py", line 18, in <module>
[Tue Mar 03 02:45:09.631993 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     from tastypie.authentication import Authentication
[Tue Mar 03 02:45:09.632022 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]   File "/usr/lib/python2.7/dist-packages/tastypie/authentication.py", line 13, in <module>
[Tue Mar 03 02:45:09.632045 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424]     from tastypie.compat import User, username_field
[Tue Mar 03 02:45:09.632072 2015] [:error] [pid 1299:tid 140148981966592] [remote 127.0.0.1:39424] ImportError: cannot import name username_field

please help to removing errors..

**Comment by simod** [comment]
@darabk I'm sorry but you cannot upgrade geonode 2.0.1 stable to 2.4 beta at this stage of development.
Migrations will be available with the stable release. 
We have a users mailing list also, which is better to get support geonode-users@lists.osgeo.org.

**Comment by darabk** [comment]
Dear simod,
I don't upgrade from 2.01 to 2.4..
I install new ubuntu 14.04 on a virtual machine an install geonode with apt-get method.

**Comment by darabk** [comment]
Dear simod,
I didn't upgrade from 2.01 to 2.4..
I installed new ubuntu 14.04 on a virtual machine an install geonode with
apt-get method.

**Comment by simod** [comment]
oh, sorry. I will test the installation today and will report back. Thanks for reporting this.

**Comment by simod** [comment]
Ok, I just installed a fresh 14.04 vm using those commands:
- sudo add-apt-repository ppa:geonode/testing
- sudo apt-get update
- sudo apt-get install geonode
- geonode createsuperuser
- sudo geonode-updateip localhost:8001 (I'm serving the vm through that port)

And everything works fine.
Ca you confirm that you used the same sequence of commands?

**Comment by darabk** [comment]
Thanks for replying..
I followed your steps too and difference is in step 5 for ip: 127.0.0.1
after all steps i succeed lunch genode 2.4b22,
but when installing geonode-project form django command and using 
https://github.com/simod/geonode-project/tree/2.4, error 500 occurred.
Attention to changes on apache to new version 2.4, I used 'Require All Granted' beside previously Order allow,deny
Allow from all

now geonode.conf has these lines:
-------
WSGIDaemonProcess geonode user=www-data threads=15 processes=2
<VirtualHost *:80>
    Servername localhost
    ServerAdmin webmaster@localhost

    ErrorLog /var/log/apache2/error.log
    LogLevel warn
    CustomLog /var/log/apache2/access.log combined

    WSGIProcessGroup geonode
    WSGIPassAuthorization On
    WSGIScriptAlias / /home/dary/my_geonode/my_geonode/wsgi.py

    <Directory "/home/dary/my_geonode/my_geonode/">
       Options Indexes FollowSymLinks
       Require all granted
       IndexOptions FancyIndexing
    </Directory>

    <Directory "/var/www/geonode/">
       Order allow,deny
        Options Indexes FollowSymLinks
        Allow from all
        IndexOptions FancyIndexing
    </Directory>

    Alias /static/ /var/www/geonode/static/
    Alias /uploaded/ /var/www/geonode/uploaded/
    Alias /robots.txt /var/www/geonode/robots.txt

    <Directory "/var/www/geonode/uploaded/documents/">
	Require all denied
    </Directory>

    <Proxy *>
       Require all granted
    </Proxy>

    ProxyPreserveHost On
    ProxyPass /geoserver http://localhost:8080/geoserver
    ProxyPassReverse /geoserver http://localhost:8080/geoserver
</VirtualHost>
--------

**Comment by darabk** [comment]
Thanks for replying..
I followed your steps too and difference is in step 5 for ip: 127.0.0.1
after all steps i succeed lunch genode 2.4b22,
but when installing geonode-project form django command and using
https://github.com/simod/geonode-project/tree/2.4, error 500 occurred.
Attention to changes on apache to new version 2.4, I used 'Require All Granted' beside previously Order allow,deny
Allow from all
now geonode.conf has these lines:

WSGIDaemonProcess geonode user=www-data threads=15 processes=2

Servername localhost
ServerAdmin webmaster@localhost

ErrorLog /var/log/apache2/error.log
LogLevel warn
CustomLog /var/log/apache2/access.log combined

WSGIProcessGroup geonode
WSGIPassAuthorization On
WSGIScriptAlias / /home/dary/my_geonode/my_geonode/wsgi.py

<Directory "/home/dary/my_geonode/my_geonode/">
   Options Indexes FollowSymLinks
   Require all granted
   IndexOptions FancyIndexing
</Directory>

<Directory "/var/www/geonode/">
   Order allow,deny
    Options Indexes FollowSymLinks
    Allow from all
    IndexOptions FancyIndexing
</Directory>

Alias /static/ /var/www/geonode/static/
Alias /uploaded/ /var/www/geonode/uploaded/
Alias /robots.txt /var/www/geonode/robots.txt

<Directory "/var/www/geonode/uploaded/documents/">
Require all denied
</Directory>

<Proxy *>
   Require all granted
</Proxy>

ProxyPreserveHost On
ProxyPass /geoserver http://localhost:8080/geoserver
ProxyPassReverse /geoserver http://localhost:8080/geoserver

**Comment by simod** [comment]
ok so here is what I did after the previous commands:
- django-admin startproject my_geonode --template=https://github.com/GeoNode/geonode-project/archive/2.4.zip -epy,rst
- sudo pip install -e my_geonode
- sudo vi /etc/apache2/sites-enabled/geonode.conf
- changed the wsgi to WSGIScriptAlias / /home/vagrant/my_geonode/my_geonode/wsgi.py
- added <Directory "/home/vagrant/my_geonode/">
        Order allow,deny
        Require all granted
        Options Indexes FollowSymLinks
        Allow from all
        IndexOptions FancyIndexing
    </Directory>
- sudo service apache2 restart
- modified a template: vi my_geonode/templates/site_index.html

and still everything works...

**Comment by darabk** [comment]
Dear Simod,
I followed these steps about 10-15 times from the first step,
[ I'm friend of Mehrdad Jef..(politecnico di torino-ITHACA) ]
and we exactly did these steps..
but before the last above steps, when test lunching geonode by localhost command in browser, got
500 Internal Server Error !
these steps for ubuntu 12.04 and geonode 2.01 are worked..OK , but not for new version of ubuntu and new generation of geonode.

but still not working..

**Comment by simod** [comment]
hm, this is strange. I'm wondering what can I do to reproduce it.

**Comment by simod** [comment]
can you give me the output of these commands?
- python
- import tastypie
- tastypie.__version__

**Comment by darabk** [comment]
dary@dar:~$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tastypie
>>> tastypie.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
>>>

**Comment by simod** [comment]
is:
```
- python
- import tastypie
- tastypie.__version__
```

**Comment by darabk** [comment]
dary@dar:~$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tastypie
>>> tastypie.__version__
(0, 9, 15)
>>>

**Comment by simod** [comment]
so we have the correct same version of tastypie.

**Comment by simod** [comment]
your django version?

```
- python
- import django
- django.VERSION
```

**Comment by darabk** [comment]
>>> import django
>>> django.VERSION
(1, 6, 1, 'final', 0)
>>>

**Comment by simod** [comment]
correct.
Let's try to debug the specific error. Try this:
```
- geonode shell
- from tastypie.compat import User, username_field
```

**Comment by darabk** [comment]
Is it noticable or not, the ubuntu version is latest LTS 14.04.2
but not worked on Ubuntu 14.04.1 too..

after commands above:
dary@dar:~$ geonode shell
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from tastypie.compat import User, username_field
>>>

**Comment by darabk** [comment]
Do I have to replace User and username_field with something else? if Yes with what?

**Comment by simod** [comment]
Did you get any errors? I don't see them and seems to work.

**Comment by darabk** [comment]
yes, still got Error :
500 Internal Server Error !

**Comment by simod** [comment]
I mean in the geonode shell, if you don't see any error there, then it works.
So the only other thing that I could imagine is something wrong with the installation. You confirm that the ubuntu was completely new and empty when you installed geonode?

**Comment by darabk** [comment]
yes, I did it for several times with different new systems
ubuntu 14.04.1 LTS
ubuntu 14.04.2 LTS
 and received the same error 500.

**Comment by darabk** [comment]
may i view your geonode.conf content file?

**Comment by simod** [comment]
```
WSGIDaemonProcess geonode user=www-data threads=15 processes=2
<VirtualHost *:80>
    Servername localhost
    ServerAdmin webmaster@localhost

    ErrorLog /var/log/apache2/error.log
    LogLevel warn
    CustomLog /var/log/apache2/access.log combined

    WSGIProcessGroup geonode
    WSGIPassAuthorization On
    WSGIScriptAlias / /home/vagrant/my_geonode/my_geonode/wsgi.py

    <Directory "/home/vagrant/my_geonode/">
        Order allow,deny
        Require all granted
        Options Indexes FollowSymLinks
        Allow from all
        IndexOptions FancyIndexing
    </Directory>

    <Directory "/var/www/geonode/">
       Order allow,deny
```

I just modified the wsgi script alias and added the directory directive.

**Comment by darabk** [comment]
content of my error
------------
500 Internal Server Error !

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache/2.4.7 (Ubuntu) Server at localhost Port 80

**Comment by simod** [comment]
I'm am suspecting a circular import in python. But dunno why it doesn't show up for me

**Comment by darabk** [comment]
I'd copied your geonode.conf content with mine and just change vargant to my user 'dary'
and still not worked..

**Comment by simod** [comment]
I'm testing again on a different vm

**Comment by darabk** [comment]
can I install geonode from first step and report you step by step ?

**Comment by simod** [comment]
can you come in IRC irc://irc.freenode.net/geonode?

**Comment by darabk** [comment]
I'm in IRC irc://irc.freenode.net/geonode with mibbit.com, correct?

**Comment by simod** [comment]
I don't see you, you can use https://kiwiirc.com/client choose freenode on the left, then type your name and #geonode as channel

**Comment by darabk** [comment]
yes, I'm connected with darab user

**Comment by simod** [comment]
closing as fixed

**Comment by darabk** [comment]
Dear Simod,
After renaming 'local_settings.py.sample' to 'local_settings.py' (inside my project), Erro 500 appeared again !
But after copying the file's content from original (/etc/geonode/) to template local_settings.py of my project, it's lunched perfectly.. is it OK or not?

**Comment by simod** [comment]
We will test why it throws that error. Anyway is ok but you don't need to do it since the original local_settings.py is still used by the geonode_project. So if the content of the fils is the same you can avoid to use the geonode_project local_settings

**Comment by simod** [comment]
Well, the error it's likely to be caused by the missing of this line in the OGC_SERVER https://github.com/GeoNode/geonode/blob/master/geonode/local_settings.py.sample#L37. Fixing.
Thanks for reporting

**Comment by darabk** [comment]
But still the Error occured..

**Comment by darabk** [comment]
after adding

import os
import geonode

in the first of file

and
'LOG_FILE':'/usr/share/geoserver/data/logs/geoserver.log',
in the OGC block

it's working..
is it OK !?

**Comment by darabk** [comment]
after adding
  import os
  import geonode
in the first of file
and
  'LOG_FILE':'/usr/share/geoserver/data/logs/geoserver.log',
in the OGC block

it's working.. is it OK !?

**Comment by simod** [comment]
is ok. By the way I have remove the local_settings.py.sample from the
project as it is actually not strictly needed.

2015-03-04 14:42 GMT+01:00 darabk <notifications@github.com>:

> after adding
> import os
> import geonode
> in the first of file
> and
> 'LOG_FILE':'/usr/share/geoserver/data/logs/geoserver.log',
> in the OGC block
>
> it's working.. is it OK !?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2090#issuecomment-77159181>.
>



-- 
Simone

**Comment by darabk** [comment]
After change the site_base.css for theming, it's not worked !

**Comment by simod** [comment]
@darabk you need to run collectstatic in order to see the changes. Please now switch to the geonode-users@lists.osgeo.org for the support :)

**Comment by darabk** [comment]
Thanks ..
I'v done collectstatic command, but it was not the problem..
because of in original css file .nav-logo block convert to .navbar-brand, and when I was trying to change logo, it wasn't work !

**Comment by abersh** [comment]
Hi simod . I install Geonode 2.0.1 on Ubuntu 12.04 and I upload layer it works. but when I view the layer to click nothing is display please help me !!!

**Comment by simod** [comment]
@abersh we released the 2.4 final last week. I suggest you to use it on ubuntu 14.04 ad it contains a lot of improvements.

**Comment by 25RUS** [comment]
Hi! My web server had error: HTTP 500 (Internal Server Error) when i used *.php, but with *.html files all was fine. To fix this problem we must change line: display_errors = Off to: display_errors = On in file /etc/php5/apache2/php.ini
My configuranion: Debian 8.2, apache 2.4.10
