### ISSUE TITLE
GeoNode 2.10.X won't start

### ISSUE THREAD

**Issue by juliermegeotube** [GeoNode/geonode#6370]
I installed geonode@2.10.X about 10 days ago. And now, I am trying to run paver start and I am getting the following errors:

at org.eclipse.jetty.runner.Runner.main(Runner.java:559)
2020-08-22 16:37:19.705:INFO:oejs.AbstractNCSARequestLog:main: Opened /opt/geonode/geoserver/jetty.log
2020-08-22 16:37:19.719:INFO:oejs.AbstractConnector:main: Started ServerConnector@5018b648{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2020-08-22 16:37:19.719:INFO:oejs.Server:main: Started @16412ms
The logs are available at /opt/geonode/geoserver/jetty.log
GeoServer never started properly or timed out.It may still be running in the background.

2 - Jetty log file extract

java.lang.NoClassDefFoundError: Could not initialize class com.ibm.icu.impl.ICUDebug

127.0.0.1 - - [22/Aug/2020:19:37:48 +0000] "GET /geoserver/ HTTP/1.1" 503 346

I am running Ubuntu_Server_18.04_LTS, GeoNode@2.10.x and Python2.7.17 and Python3.6.9

Everything was fine about a week ago. But by now I am hitting this issue.

**Comment by t-book** [comment]
Which Java do you run?

**Comment by juliermegeotube** [comment]
@t-book, I am running openjdk version "1.8.0_265". I am very successful working on GeoNode@3.0. I realized that when cloning git clone https://github.com/GeoNode/geonode-project.git -b 2.10.4 geonode. The shell shows git # 3.0 (GeoNode@3.0). I may be wrong, but I realized that  when we install virtualenv system wide for geonode system packages, ubuntu get python2 installed and things get very messed up with python3. Now, I am installing virtualenv and virtualenvwrapper through pip3 install. 
Now, I think I am getting on the rail track to install geonode and geonode-project 3.0. I will close this issue. Thank you very much.
