### ISSUE TITLE
Leaflet not working in 2.7 and 2.8

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#3873]
Hi,

has one tested  leaflet hook ? I´ve installed geonode 2.7 and 2.8 with geonode_project and enabled in settings:

```
GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY = 'leaflet'
GEONODE_CLIENT_HOOKSET = "geonode.client.hooksets.LeafletHookSet"
```

On a layers Detail, the map stays just empty without any errors in console.
On maps detail nothing is happening, menu is not working and the select stays empty. Console shows:

```
2:771 Uncaught TypeError: L.easyButton is not a function
   ...

2:2460 Uncaught TypeError: $(...).select2 is not a function
    ...
```

If somebody can confirm this mabye an admin can add the bug label?

**Comment by t-book** [comment]
**For Layers Detail:**
The map stays empy as  `{{ layer_bbox }};` [1] is not set.
if I set it for testing `zoom_to_box(map, [42.0468718,2.7438793000000032,41.219172,1.6023217]);`
it works.

[1] https://github.com/GeoNode/geonode/blob/master/geonode/client/templates/leaflet/layers/layer_leaflet_map.html#L178

**Comment by t-book** [comment]
**For Maps Detail:**
There is something wrong with template inheritance:
The head can be found twice in source:


```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta Http-Equiv="Cache-Control" Content="no-cache">
    <meta Http-Equiv="Pragma" Content="no-cache">
    <meta Http-Equiv="Expires" Content="0">
    <meta Http-Equiv="Pragma-directive: no-cache">
    <meta Http-Equiv="Cache-directive: no-cache">
    

    <title>XXX —  example.com </title>
    
  
    <meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@GeoNode" />
<!-- Twitter truncates twitter:title to 70 characters. -->
<meta name="twitter:title" content="XXX" />
<!-- Twitter truncates twitter:description at the word to 200 characters. -->
<meta name="twitter:description" content="Map on example.com by admin" />
<meta name="twitter:image" content="http://localhost:8000/uploaded/thumbs/map-d6fd298f-9fd0-11e8-977d-5cf9389c28be-thumb.png" />

  
  
    <meta property="og:title" content="XXX" />
<meta property="og:site_name" content="example.com" />
<meta property="og:url" content="http://example.com/maps/2" />
<meta property="og:description" content="Map on example.com by admin" />
<meta name="og:image" content="http://localhost:8000/uploaded/thumbs/map-d6fd298f-9fd0-11e8-977d-5cf9389c28be-thumb.png" />
<meta name="og:image:width" content="200" />
<meta name="og:image:height" content="150" />

  

  

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta Http-Equiv="Cache-Control" Content="no-cache">
    <meta Http-Equiv="Pragma" Content="no-cache">
    <meta Http-Equiv="Expires" Content="0">
    <meta Http-Equiv="Pragma-directive: no-cache">
    <meta Http-Equiv="Cache-directive: no-cache">
```

**Comment by t-book** [comment]
@francbartoli Francesco can you kindly add the  bug label to this issue?

**Comment by francbartoli** [comment]
@t-book done

**Comment by t-book** [comment]
@francbartoli grazie!
